### ISSUE TITLE
Consider FFI instead of XS

### ISSUE THREAD

**Issue by shawnlaffan** [johannessen/cs2cs-perl#1]
Just a comment on the possible XS interface noted in the POD.

If you do implement such a direct interface, it is probably simpler to use FFI via [FFI::Platypus](https://metacpan.org/pod/FFI::Platypus) instead of XS.  See for example [Geo::GDAL::FFI](https://metacpan.org/pod/Geo::GDAL::FFI).

Regards,
Shawn.

**Comment by johannessen** [comment]
Thanks a lot for the pointer! I had just found out about FFI::Platypus earlier today and will consider it. That said, any kind of FFI / XS work is not on my agenda for this module anytime soon.

**Comment by shawnlaffan** [comment]
No problem.  The docs are pretty clear that it's a low priority.

Feel free to close this issue.

**Comment by johannessen** [comment]
Addressed through [release 1.02](https://metacpan.org/release/AJNN/Geo-LibProj-cs2cs-1.02). Thanks again!
